spring:
  application:
    name: mscartoes
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
  rabbitmq:
    host: localhost
#    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest
    
    
server:
  port: 0
  
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka
#      defaultZone: http://admin:admin@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      
      
mq:
  queues:
    emissao-cartoes: emissao-cartoes